### ISSUE TITLE
As a user, I should be able to open multiple PRs

### ISSUE THREAD

**Issue by adamjonas** [tvpeter/yt2btc#23]
I can't have more than 1 PR open

<img width="658" alt="Screen Shot 2023-01-06 at 11 40 59 AM" src="https://user-images.githubusercontent.com/755825/211057348-6ed3741f-ebca-45fd-95c9-eb1cdcc86c9a.png">

<img width="830" alt="Screen Shot 2023-01-06 at 11 48 45 AM" src="https://user-images.githubusercontent.com/755825/211058512-a8e4b74f-41a1-487b-b9f9-77405d5eefdb.png">

**Comment by tvpeter** [comment]
I just noticed that the arguments you were passing seemed to be incomplete. I assumed that it was always going to be something like `yt2btc {video_id} {event_name}/{year}` so, your input should have been `yt2btc rrr_zRmeiMe misc/2022`

**Comment by tvpeter** [comment]
Alright, I will test a similar use case
