### ISSUE TITLE
It appears I have to be on another branch other than master?

### ISSUE THREAD

**Issue by adamjonas** [tvpeter/yt2btc#3]
<img width="838" alt="Screen Shot 2023-01-02 at 2 47 40 PM" src="https://user-images.githubusercontent.com/755825/210273345-62dadeb7-9616-40d7-bd44-d1b0c9289173.png">

I wasn't able to push because I was on the master branch

**Comment by tvpeter** [comment]
yes, because the base branch which the PR will be opened will be master on bitcointranscripts

**Comment by adamjonas** [comment]
Tried changing the y2btc branch named test with the same result.

<img width="849" alt="Screen Shot 2023-01-02 at 3 02 19 PM" src="https://user-images.githubusercontent.com/755825/210274103-56543810-b47e-49bd-ac32-87aeffbd4085.png">

Then realized you must mean that I need to cd into the cloned bitcointranscripts dir and change that branch which I did.

I got a little farther but it still failed:
<img width="766" alt="Screen Shot 2023-01-02 at 3 05 30 PM" src="https://user-images.githubusercontent.com/755825/210274322-9849f90e-130c-4015-8276-71d12a7486ef.png">
